<a href="https://colab.research.google.com/github/Ankit25128/Number-/blob/main/assignment_mod_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Module 2: Case-Based Lab Assignment
Namne:Ankit Raj
Roll no:BETN1AI25128
Colab Link:

https://colab.research.google.com/drive/1aX526p3bDny-D8BGsoRblY1kvn7UDknL#scrollTo=cpS786pzlZ4u

Git Hub:




Case Study 1: Student Marks Analysis
Dataset:
marks = np.array([
 [80, 75, 90],
 [60, 88, 70],
 [95, 92, 85],
 [70, 65, 60],
 [88, 78, 84]
])
Tasks:
1. Compute total marks of each student.
2. Calculate average marks per student.
3. IdenƟfy topper using NumPy.
4. Find subject-wise highest score.
5. Compute standard deviation of each subject.
6. Comment on performance consistency.


In [16]:
marks = np.array([
 [80, 75, 90],
 [60, 88, 70],
 [95, 92, 85],
 [70, 65, 60],
 [88, 78, 84]
])
#1. Compute total marks of each student.
import numpy as np
total_marks = np.sum(marks, axis=1)
print(total_marks)

#2. Calculate average marks per student.
average_marks = np.mean(marks, axis=1)
print(average_marks)

#3. Identify topper using NumPy.
topper_index = np.argmax(total_marks)
print("Topper is Student", topper_index + 1)

#4. Find subject-wise highest score.

highest_subject = np.max(marks, axis=0)
print(highest_subject)

#5. Compute standard deviation of each subject.
std_subject = np.std(marks, axis=0)
print(std_subject)



[245 218 272 195 250]
[81.66666667 72.66666667 90.66666667 65.         83.33333333]
Topper is Student 3
[95 92 90]
[12.48358923  9.60416576 11.1067547 ]


**Interpretation(Case Study:1)**

The total and average marks help evaluate the overall academic performance of each student.
Using np.argmax(), we identified the topper efficiently without manual comparison.
Subject-wise standard deviation shows variation in student performance across subjects.
A lower standard deviation indicates consistent performance, while a higher value suggests performance differences among students.
NumPy's vectorized operations make these calculations fast and efficient.

**Comment on Performance Consistency**

The standard deviation values suggest that Subject 2 is the most consistent subject because it has the lowest variation in marks.
Subject 1 shows slightly higher variation compared to others.
Overall, student performance is reasonably stable with moderate differences in marks.
There are no extreme outliers, indicating balanced academic performance across the class.

Case Study 3: Sales Analysis
Dataset:
sales = np.array([1200, 1500, 1100, 1700, 1600, 1800, 1400])
Tasks:
1. Compute average daily sales.
2. Find day with highest sales.
3. Calculate percentage growth from Day 1 to Day 7.
4. Compute cumulative sales.
5. Calculate standard deviation.
6. Interpret sales growth paƩern.

In [18]:
sales = np.array([1200, 1500, 1100, 1700, 1600, 1800, 1400])
#1. Compute average daily sales.
avg_sales = np.mean(sales)
print(avg_sales)

#2. Find day with highest sales.
highest_day = np.argmax(sales) + 1
print("Highest Sales Day:", highest_day)

#3.Calculate percentage growth from Day 1 to Day 7.
percentage_growth = ((sales[-1] - sales[0]) / sales[0]) * 100
print(percentage_growth)

#4. Compute cumulaƟve sales.
cumulative_sales = np.cumsum(sales)
print(cumulative_sales)

#5. Calculate standard deviaƟon.
std_sales = np.std(sales)
print(std_sales)



1471.4285714285713
Highest Sales Day: 6


**Interpretation(Case Study:3)**

The average daily sales provide insight into overall weekly business performance.
Using np.argmax(), we identified the peak sales day quickly.
The percentage growth calculation shows whether the business improved or declined over the week.
Cumulative sales help track total revenue progression over time.
Standard deviation indicates how stable or fluctuating the daily sales were.




**Conclusion**

From the student marks and sales datasets, we derived insights about overall performance, trends, and consistency using NumPy functions.

Most used numpy functions:

np.mean(),

np.sum(),

np.std(), and

np.argmax()

Numerical computation helps in data analytics:

Numerical computation helps in analyzing large datasets efficiently and supports accurate, data-driven decision making in real-world applications.