<a href="https://colab.research.google.com/github/Ankit25128/Number-/blob/main/Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name:Ankit Raj

Roll No.:BETN1AI25128
COLAB LINK:https://colab.research.google.com/drive/16WkYBRBXVHHBX7fkbSLmMfOcDwHKuuAm#scrollTo=sXJrVobSE_9i


In [ ]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [12]:
# Create required arrays here

# 1D array of 10 integers
import numpy as np
arr=np.array([1,2,4,5,6,7,8,9,10,11])
print(arr)

# 3x3 matrix
import numpy as np
ankit= np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print(ankit)


# Identity matrix of size 4
import numpy as np
i_matrix = np.eye(4, dtype=int)
print(i_matrix)


# Random 5x5 matrix
import numpy as np
arr = np.random.randint(0, 10, (5, 5))
print(arr)


[ 1  2  4  5  6  7  8  9 10 11]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[6 4 2 6 2]
 [4 9 2 2 2]
 [2 5 5 3 9]
 [5 6 6 6 4]
 [6 6 9 6 4]]


## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [40]:
A = np.arange(1, 26).reshape(5,5)
print(A)

# Extract 2nd row
print("Extract 2nd row")

secnd_row = A[1]
print(secnd_row)

# Extract 3rd column
print("Extract 3rd colmn")
thrd_colmn=A[:,2]
print(thrd_colmn)

# Extract 2x2 center matrix
print("2x2 matrix")
centr = A[2:4,2:4]
print(centr)


# Reverse last row
print("reversing last Row")
rev_last_row = A[-1][::-1]
print(rev_last_row)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Extract 2nd row
[ 6  7  8  9 10]
Extract 3rd colmn
[ 3  8 13 18 23]
2x2 matrix
[[13 14]
 [18 19]]
reversing last Row
[25 24 23 22 21]


## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [46]:

# Perform broadcasting operations here


# Add scalar 10 to matrix
import numpy as np
Add = A + 10
print(Add)

# Add vector [1,2,3,4,5] to each row
import numpy as np
add= np.array([1,2,3,4,5])
arr = A + add
print(arr)

# Normalize matrix between 0 and 1
A_norm = (A - A.min()) / (A.max() - A.min())
print(A_norm)


[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]
[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [64]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

# Element-wise multiplication
multi= X * Y
print(multi)

# Dot product
dot = np.dot(X, Y)
print(dot)

# Mean and Standard Deviation
import numpy as np
mean_X =np.mean(X)
mean_Y = np.mean(Y)
print("Mean of X:", mean_X)
print("Mean of Y:", mean_Y)
print(f"standrd deviation:{sd:.2f}")

[ 5 12 21 32]
70
Mean of X: 2.5
Mean of Y: 6.5
standrd deviation:1.12


Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [66]:
marks = np.array([[80,75,90],[60,88,70],[95,92,85],[70,65,60],[88,78,84]])
# Compute totals, averages, topper
#TOTAL
total = np.sum(marks, axis=1)
print("Total Marks:", total)
#AVG
average = np.mean(marks, axis=1)
print("Avg Maarks:", average)
#TOPPER
topper = np.max(total)
print("Topper: Student", topper+ 1)
print(" Topper Marks:", total[topper])



Total Marks: [245 218 272 195 250]
Avg Maarks: [81.66666667 72.66666667 90.66666667 65.         83.33333333]
Topper: Student 3
 Topper Marks: 272
